package Archivos;

import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Carmen B
 */
public class VentanaArchivos extends javax.swing.JFrame {

    DefaultListModel directorio;
    DefaultListModel archivo;
    DefaultListModel oculto;

    /**
     * Creates new form VentanaArchivos
     */
    public VentanaArchivos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnListar = new javax.swing.JButton();
        txtRutas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaDirectorios = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaArchivos = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaOcultos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblRutaAbsoluta = new javax.swing.JLabel();
        lblUltimaModficacion = new javax.swing.JLabel();
        lblTamano = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemNuevoAchivo = new javax.swing.JMenuItem();
        menuItemNuevaCarpeta = new javax.swing.JMenuItem();
        menuItemRenombrar = new javax.swing.JMenuItem();
        menuItemEliminar = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ruta"));

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        jLabel2.setText("Ruta:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRutas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListar)
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListar)
                    .addComponent(txtRutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Archivos"));

        listaDirectorios.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                listaDirectoriosAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        listaDirectorios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaDirectoriosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaDirectorios);

        listaArchivos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaArchivosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaArchivos);

        listaOcultos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaOcultosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listaOcultos);

        jLabel1.setText("Directorios");

        jLabel3.setText("Archivos");

        jLabel4.setText("Ocultos");

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(108, 108, 108)
                .addComponent(jLabel4)
                .addGap(95, 95, 95))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(btnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion"));

        lblRutaAbsoluta.setText("Ruta Absoluta:");

        lblUltimaModficacion.setText("Ultima Fecha de Modificacion:");

        lblTamano.setText("Tamaño(KB):");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRutaAbsoluta)
                    .addComponent(lblUltimaModficacion)
                    .addComponent(lblTamano))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRutaAbsoluta)
                .addGap(18, 18, 18)
                .addComponent(lblUltimaModficacion)
                .addGap(18, 18, 18)
                .addComponent(lblTamano)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Archivos");

        menuItemNuevoAchivo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mateo Robalino\\Pictures\\crear archivo.png")); // NOI18N
        menuItemNuevoAchivo.setText("Nuevo Archivo");
        menuItemNuevoAchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNuevoAchivoActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemNuevoAchivo);

        menuItemNuevaCarpeta.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mateo Robalino\\Pictures\\carpeta.jpg")); // NOI18N
        menuItemNuevaCarpeta.setText("Nueva Carpeta");
        menuItemNuevaCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNuevaCarpetaActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemNuevaCarpeta);

        menuItemRenombrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mateo Robalino\\Pictures\\renombrar.png")); // NOI18N
        menuItemRenombrar.setText("Renombrar");
        menuItemRenombrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRenombrarActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemRenombrar);

        menuItemEliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mateo Robalino\\Pictures\\elimiar.jpg")); // NOI18N
        menuItemEliminar.setText("Eliminar");
        menuItemEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEliminarActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemEliminar);

        jMenuBar1.add(jMenu1);

        menuSalir.setText("Salir");
        menuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSalirMouseClicked(evt);
            }
        });
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        String rutaTexto = txtRutas.getText().trim();
        listarArchivos(rutaTexto);
    }//GEN-LAST:event_btnListarActionPerformed

    private void listaDirectoriosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_listaDirectoriosAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_listaDirectoriosAncestorAdded

    private void listaDirectoriosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaDirectoriosValueChanged
        // TODO add your handling code here:
        String elementoSeleccionado = (String) listaDirectorios.getSelectedValue();
        String rutaSeleccionada = txtRutas.getText().trim() + "\\" + elementoSeleccionado;
        mostrarInformacionArchivoSeleccionado(rutaSeleccionada);

        listaArchivos.clearSelection();
        listaOcultos.clearSelection();
    }//GEN-LAST:event_listaDirectoriosValueChanged

    private void listaArchivosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaArchivosValueChanged
        // TODO add your handling code here:'
        String elementoSeleccionado = (String) listaArchivos.getSelectedValue();
        String rutaSeleccionada = txtRutas.getText().trim() + "\\" + elementoSeleccionado;
        mostrarInformacionArchivoSeleccionado(rutaSeleccionada);

        listaDirectorios.clearSelection();
        listaOcultos.clearSelection();
    }//GEN-LAST:event_listaArchivosValueChanged

    private void listaOcultosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaOcultosValueChanged
        // TODO add your handling code here:

        String elementoSeleccionado = (String) listaOcultos.getSelectedValue();
        String rutaSeleccionada = txtRutas.getText().trim() + "\\" + elementoSeleccionado;
        mostrarInformacionArchivoSeleccionado(rutaSeleccionada);

        listaArchivos.clearSelection();
        listaDirectorios.clearSelection();
    }//GEN-LAST:event_listaOcultosValueChanged

    private void menuItemNuevoAchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNuevoAchivoActionPerformed
        // TODO add your handling code here:
        String nombreArchivo = JOptionPane.showInputDialog("Ingrese el nombre del archivo:");
        String ruta = txtRutas.getText().trim() + "\\" + nombreArchivo;

        File archivoNuevo = new File(ruta);
        if (!archivoNuevo.exists()) {
            try {
                archivoNuevo.createNewFile();
            } catch (IOException ex) {
                System.err.println("Error: archivo no pudo ser creado");
            }
        }

        // trim elimina espacios tanto de derecha como izquierda
        listarArchivos(txtRutas.getText().trim());
    }//GEN-LAST:event_menuItemNuevoAchivoActionPerformed

    private void menuItemRenombrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRenombrarActionPerformed
        // TODO add your handling code here:
        String archivoSeleccionado = null;
        if (!listaArchivos.isSelectionEmpty()) {
            archivoSeleccionado = (String) listaArchivos.getSelectedValue();
        } else if (!listaDirectorios.isSelectionEmpty()) {
            archivoSeleccionado = (String) listaDirectorios.getSelectedValue();
        } else {
            archivoSeleccionado = (String) listaOcultos.getSelectedValue();
        }

        String rutaArchivoSeleccionado = txtRutas.getText().trim() + "\\" + archivoSeleccionado;
        File archivo = new File(rutaArchivoSeleccionado);

        String nombreNuevoArchivo = JOptionPane.showInputDialog("Ingrese el nuevo nombre del archivo:");
        String rutaNuevoArchivo = txtRutas.getText().trim() + "\\" + nombreNuevoArchivo;
        File archivoNuevo = new File(rutaNuevoArchivo);

        if (archivoNuevo.exists()) {
            JOptionPane.showMessageDialog(this, "Ya existe un archivo con ese nombre");
        } else {
            archivo.renameTo(archivoNuevo);
        }

        listarArchivos(txtRutas.getText().trim());
    }//GEN-LAST:event_menuItemRenombrarActionPerformed

    private void menuItemNuevaCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNuevaCarpetaActionPerformed
        // TODO add your handling code here:
        String nombreDirectorio = JOptionPane.showInputDialog("Ingresa el nombre de la nueva carpeta");
        String ruta = txtRutas.getText().trim() + "\\" + nombreDirectorio;
        File directorio = new File(ruta);
        if (directorio.exists()) {
            JOptionPane.showMessageDialog(this, "El directorio ya existe en la ruta");
        } else {
            directorio.mkdir();
        }
        listarArchivos(txtRutas.getText().trim());
    }//GEN-LAST:event_menuItemNuevaCarpetaActionPerformed

    private void menuItemEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEliminarActionPerformed
        // TODO add your handling code here:
        String archivoSeleccionado = null;
        boolean isValid = true;

        if (!listaArchivos.isSelectionEmpty()) {
            archivoSeleccionado = (String) listaArchivos.getSelectedValue();
        } else if (!listaDirectorios.isSelectionEmpty()) {
            archivoSeleccionado = (String) listaDirectorios.getSelectedValue();
        } else if (!listaOcultos.isSelectionEmpty()) {
            archivoSeleccionado = (String) listaOcultos.getSelectedValue();
        } else {

            isValid = false;
            JOptionPane.showMessageDialog(this, "No has seleccionado un archivo para eliminar");
        }

        if (isValid) {

            String rutaArchivoSeleccionado = txtRutas.getText().trim() + "\\" + archivoSeleccionado;
            File archivo = new File(rutaArchivoSeleccionado);
            //archivo.delete();
            eliminarTodo(archivo);
            JOptionPane.showMessageDialog(this, "Eliminado Correcmente");
            listarArchivos(txtRutas.getText().trim());
        }
    }//GEN-LAST:event_menuItemEliminarActionPerformed

    
    private void eliminarTodo(File file) {
        if (file.isDirectory()) {

            if (file.list().length==0) {
                file.delete();
            } else {
                for (String f : file.list()) {
                    File eliminar=new File(file,f);

                    //Recursividad
                    eliminarTodo(eliminar);

                }
                if (file.list().length==0) {
                    file.delete();
                }
            }
        } else {
            file.delete();
        }

    }
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        
      String r=txtRutas.getText().trim();
        for (int i=r.length()-1;i>1;i--){
           if ((int)txtRutas.getText().trim().charAt(i)==92){
               r=txtRutas.getText().trim().substring(0,i);
               txtRutas.setText(r);
               btnListarActionPerformed(evt);
               break;
           }
        }
    
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        // TODO add your handling code here:
        
      
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuSalirMouseClicked

   

    private void listarArchivos(String rutaTexto) {
        directorio = new DefaultListModel();
        listaDirectorios.setModel(directorio);

        archivo = new DefaultListModel();
        listaArchivos.setModel(archivo);

        oculto = new DefaultListModel();
        listaOcultos.setModel(oculto);

        if (!rutaTexto.equals("")) {
            File ruta = new File(rutaTexto);
            if (ruta.exists()) {
                File[] archivos = ruta.listFiles();

                for (File archivo : archivos) {

                    if (archivo.isDirectory()) {
                        if (archivo.isHidden()) {
                            // System.out.println("Ocultos " + archivo.getName());
                            String lista = archivo.getName();
                            oculto.addElement(lista);

                        } else {
                            // System.out.println("Directorios " + archivo.getName());
                            String lista = archivo.getName();
                            directorio.addElement(lista);
                        }

                    } else if (archivo.isFile()) {
                        if (archivo.isHidden()) {
                            //System.out.println("Ocultos " + archivo.getName());
                            String lista = archivo.getName();
                            oculto.addElement(lista);

                        } else {
                            // System.out.println("Archivos " + archivo.getName());
                            String lista = archivo.getName();
                            this.archivo.addElement(lista);
                        }

                    }

                }
            } else {
                JOptionPane.showMessageDialog(this, "Ruta no encontrada");
            }
        }

    }

    private void mostrarInformacionArchivoSeleccionado(String rutaSeleccionada) {
        File archivoSeleccionado = new File(rutaSeleccionada);
        long fechaMilisegundos = archivoSeleccionado.lastModified();
        Date fecha = new Date(fechaMilisegundos);
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        String fechaTexto = formato.format(fecha);
        lblUltimaModficacion.setText("Fecha de ultima modificacion: " + fechaTexto);

        //obtengo la ruta absoluta
        String rutaAbsoluta = archivoSeleccionado.getAbsolutePath();
        lblRutaAbsoluta.setText("Ruta absoluta: " + rutaAbsoluta);

        //obtengo el tamano del archivo en kb
        long tamanoEnBytes = archivoSeleccionado.length();
        long tamanoEnKBytes = tamanoEnBytes / 1024l;

        lblTamano.setText("Tamaño (Kb): " + tamanoEnKBytes);
        
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaArchivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaArchivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblRutaAbsoluta;
    private javax.swing.JLabel lblTamano;
    private javax.swing.JLabel lblUltimaModficacion;
    private javax.swing.JList<String> listaArchivos;
    private javax.swing.JList<String> listaDirectorios;
    private javax.swing.JList<String> listaOcultos;
    private javax.swing.JMenuItem menuItemEliminar;
    private javax.swing.JMenuItem menuItemNuevaCarpeta;
    private javax.swing.JMenuItem menuItemNuevoAchivo;
    private javax.swing.JMenuItem menuItemRenombrar;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JTextField txtRutas;
    // End of variables declaration//GEN-END:variables

}
